apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-blue
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: webserver
        color: blue
    spec:
      containers:
      - image: 192.168.99.1:5000/rmrbest/spring-boot-playground
        name: spring-boot-container
        ports:
        - containerPort: 80
          name: http-server
